color red, TPIS_CANAL and resi 16
color red, TPIS_CANAL and resi 25
color red, TPIS_CANAL and resi 27
color red, TPIS_CANAL and resi 29
color red, TPIS_CANAL and resi 34
color red, TPIS_CANAL and resi 36
color red, TPIS_CANAL and resi 39
color red, TPIS_CANAL and resi 43
color red, TPIS_CANAL and resi 44
color red, TPIS_CANAL and resi 45
color red, TPIS_CANAL and resi 46
color red, TPIS_CANAL and resi 47
color red, TPIS_CANAL and resi 60
color red, TPIS_CANAL and resi 68
color red, TPIS_CANAL and resi 69
color red, TPIS_CANAL and resi 78
color red, TPIS_CANAL and resi 84
color red, TPIS_CANAL and resi 88
color red, TPIS_CANAL and resi 89
color red, TPIS_CANAL and resi 95
color red, TPIS_CANAL and resi 100
color red, TPIS_CANAL and resi 105
color red, TPIS_CANAL and resi 113
color red, TPIS_CANAL and resi 114
color red, TPIS_CANAL and resi 116
color red, TPIS_CANAL and resi 117
color red, TPIS_CANAL and resi 118
color red, TPIS_CANAL and resi 121
color red, TPIS_CANAL and resi 130
color red, TPIS_CANAL and resi 138
color red, TPIS_CANAL and resi 140
color red, TPIS_CANAL and resi 144
color red, TPIS_CANAL and resi 147
color red, TPIS_CANAL and resi 151
color red, TPIS_CANAL and resi 152
color red, TPIS_CANAL and resi 164
color red, TPIS_CANAL and resi 175
color red, TPIS_CANAL and resi 177
color red, TPIS_CANAL and resi 184
color red, TPIS_CANAL and resi 185
color red, TPIS_CANAL and resi 192
color red, TPIS_CANAL and resi 193
color red, TPIS_CANAL and resi 194
color red, TPIS_CANAL and resi 198
color red, TPIS_CANAL and resi 204
color red, TPIS_CANAL and resi 207
color red, TPIS_CANAL and resi 208
color red, TPIS_CANAL and resi 215
color red, TPIS_CANAL and resi 218
color red, TPIS_CANAL and resi 222
color red, TPIS_CANAL and resi 231
