color red, TPIS_SCHMA and resi 5
color red, TPIS_SCHMA and resi 12
color red, TPIS_SCHMA and resi 16
color red, TPIS_SCHMA and resi 21
color red, TPIS_SCHMA and resi 22
color red, TPIS_SCHMA and resi 26
color red, TPIS_SCHMA and resi 29
color red, TPIS_SCHMA and resi 37
color red, TPIS_SCHMA and resi 47
color red, TPIS_SCHMA and resi 50
color red, TPIS_SCHMA and resi 53
color red, TPIS_SCHMA and resi 61
color red, TPIS_SCHMA and resi 63
color red, TPIS_SCHMA and resi 65
color red, TPIS_SCHMA and resi 67
color red, TPIS_SCHMA and resi 74
color red, TPIS_SCHMA and resi 75
color red, TPIS_SCHMA and resi 76
color red, TPIS_SCHMA and resi 79
color red, TPIS_SCHMA and resi 82
color red, TPIS_SCHMA and resi 92
color red, TPIS_SCHMA and resi 94
color red, TPIS_SCHMA and resi 101
color red, TPIS_SCHMA and resi 109
color red, TPIS_SCHMA and resi 115
color red, TPIS_SCHMA and resi 117
color red, TPIS_SCHMA and resi 118
color red, TPIS_SCHMA and resi 122
color red, TPIS_SCHMA and resi 126
color red, TPIS_SCHMA and resi 131
color red, TPIS_SCHMA and resi 140
color red, TPIS_SCHMA and resi 144
color red, TPIS_SCHMA and resi 152
color red, TPIS_SCHMA and resi 163
color red, TPIS_SCHMA and resi 165
color red, TPIS_SCHMA and resi 167
color red, TPIS_SCHMA and resi 176
color red, TPIS_SCHMA and resi 181
color red, TPIS_SCHMA and resi 183
color red, TPIS_SCHMA and resi 184
color red, TPIS_SCHMA and resi 186
color red, TPIS_SCHMA and resi 191
color red, TPIS_SCHMA and resi 192
color red, TPIS_SCHMA and resi 200
color red, TPIS_SCHMA and resi 211
color red, TPIS_SCHMA and resi 219
color red, TPIS_SCHMA and resi 226
color red, TPIS_SCHMA and resi 227
color red, TPIS_SCHMA and resi 230
color red, TPIS_SCHMA and resi 244
color red, TPIS_SCHMA and resi 250
color red, TPIS_SCHMA and resi 252
