color red, TPIS_SCHJA and resi 5
color red, TPIS_SCHJA and resi 10
color red, TPIS_SCHJA and resi 17
color red, TPIS_SCHJA and resi 20
color red, TPIS_SCHJA and resi 21
color red, TPIS_SCHJA and resi 22
color red, TPIS_SCHJA and resi 36
color red, TPIS_SCHJA and resi 37
color red, TPIS_SCHJA and resi 44
color red, TPIS_SCHJA and resi 46
color red, TPIS_SCHJA and resi 49
color red, TPIS_SCHJA and resi 53
color red, TPIS_SCHJA and resi 55
color red, TPIS_SCHJA and resi 67
color red, TPIS_SCHJA and resi 74
color red, TPIS_SCHJA and resi 77
color red, TPIS_SCHJA and resi 79
color red, TPIS_SCHJA and resi 94
color red, TPIS_SCHJA and resi 99
color red, TPIS_SCHJA and resi 106
color red, TPIS_SCHJA and resi 109
color red, TPIS_SCHJA and resi 117
color red, TPIS_SCHJA and resi 118
color red, TPIS_SCHJA and resi 119
color red, TPIS_SCHJA and resi 122
color red, TPIS_SCHJA and resi 123
color red, TPIS_SCHJA and resi 126
color red, TPIS_SCHJA and resi 129
color red, TPIS_SCHJA and resi 132
color red, TPIS_SCHJA and resi 163
color red, TPIS_SCHJA and resi 167
color red, TPIS_SCHJA and resi 175
color red, TPIS_SCHJA and resi 192
color red, TPIS_SCHJA and resi 203
color red, TPIS_SCHJA and resi 205
color red, TPIS_SCHJA and resi 211
color red, TPIS_SCHJA and resi 214
color red, TPIS_SCHJA and resi 217
color red, TPIS_SCHJA and resi 218
color red, TPIS_SCHJA and resi 219
color red, TPIS_SCHJA and resi 232
