color red, TPIS_CHICK and resi 4
color red, TPIS_CHICK and resi 5
color red, TPIS_CHICK and resi 13
color red, TPIS_CHICK and resi 18
color red, TPIS_CHICK and resi 19
color red, TPIS_CHICK and resi 21
color red, TPIS_CHICK and resi 27
color red, TPIS_CHICK and resi 28
color red, TPIS_CHICK and resi 32
color red, TPIS_CHICK and resi 34
color red, TPIS_CHICK and resi 44
color red, TPIS_CHICK and resi 53
color red, TPIS_CHICK and resi 54
color red, TPIS_CHICK and resi 58
color red, TPIS_CHICK and resi 68
color red, TPIS_CHICK and resi 70
color red, TPIS_CHICK and resi 71
color red, TPIS_CHICK and resi 93
color red, TPIS_CHICK and resi 99
color red, TPIS_CHICK and resi 108
color red, TPIS_CHICK and resi 111
color red, TPIS_CHICK and resi 112
color red, TPIS_CHICK and resi 130
color red, TPIS_CHICK and resi 131
color red, TPIS_CHICK and resi 134
color red, TPIS_CHICK and resi 139
color red, TPIS_CHICK and resi 141
color red, TPIS_CHICK and resi 146
color red, TPIS_CHICK and resi 155
color red, TPIS_CHICK and resi 158
color red, TPIS_CHICK and resi 159
color red, TPIS_CHICK and resi 180
color red, TPIS_CHICK and resi 182
color red, TPIS_CHICK and resi 187
color red, TPIS_CHICK and resi 188
color red, TPIS_CHICK and resi 189
color red, TPIS_CHICK and resi 202
color red, TPIS_CHICK and resi 205
color red, TPIS_CHICK and resi 218
color red, TPIS_CHICK and resi 220
color red, TPIS_CHICK and resi 223
color red, TPIS_CHICK and resi 237
