color red, TPIS_MAIZE and resi 6
color red, TPIS_MAIZE and resi 8
color red, TPIS_MAIZE and resi 9
color red, TPIS_MAIZE and resi 16
color red, TPIS_MAIZE and resi 17
color red, TPIS_MAIZE and resi 31
color red, TPIS_MAIZE and resi 46
color red, TPIS_MAIZE and resi 51
color red, TPIS_MAIZE and resi 57
color red, TPIS_MAIZE and resi 60
color red, TPIS_MAIZE and resi 63
color red, TPIS_MAIZE and resi 70
color red, TPIS_MAIZE and resi 78
color red, TPIS_MAIZE and resi 87
color red, TPIS_MAIZE and resi 100
color red, TPIS_MAIZE and resi 102
color red, TPIS_MAIZE and resi 103
color red, TPIS_MAIZE and resi 110
color red, TPIS_MAIZE and resi 115
color red, TPIS_MAIZE and resi 118
color red, TPIS_MAIZE and resi 122
color red, TPIS_MAIZE and resi 138
color red, TPIS_MAIZE and resi 142
color red, TPIS_MAIZE and resi 160
color red, TPIS_MAIZE and resi 162
color red, TPIS_MAIZE and resi 170
color red, TPIS_MAIZE and resi 182
color red, TPIS_MAIZE and resi 193
color red, TPIS_MAIZE and resi 199
color red, TPIS_MAIZE and resi 201
color red, TPIS_MAIZE and resi 207
color red, TPIS_MAIZE and resi 209
color red, TPIS_MAIZE and resi 215
color red, TPIS_MAIZE and resi 219
color red, TPIS_MAIZE and resi 221
color red, TPIS_MAIZE and resi 239
color red, TPIS_MAIZE and resi 244
color red, TPIS_MAIZE and resi 246
color red, TPIS_MAIZE and resi 250
