color red, TPIS_RAT and resi 2
color red, TPIS_RAT and resi 5
color red, TPIS_RAT and resi 6
color red, TPIS_RAT and resi 14
color red, TPIS_RAT and resi 18
color red, TPIS_RAT and resi 19
color red, TPIS_RAT and resi 22
color red, TPIS_RAT and resi 29
color red, TPIS_RAT and resi 33
color red, TPIS_RAT and resi 34
color red, TPIS_RAT and resi 35
color red, TPIS_RAT and resi 39
color red, TPIS_RAT and resi 40
color red, TPIS_RAT and resi 44
color red, TPIS_RAT and resi 53
color red, TPIS_RAT and resi 54
color red, TPIS_RAT and resi 55
color red, TPIS_RAT and resi 56
color red, TPIS_RAT and resi 62
color red, TPIS_RAT and resi 65
color red, TPIS_RAT and resi 70
color red, TPIS_RAT and resi 80
color red, TPIS_RAT and resi 85
color red, TPIS_RAT and resi 92
color red, TPIS_RAT and resi 93
color red, TPIS_RAT and resi 94
color red, TPIS_RAT and resi 99
color red, TPIS_RAT and resi 100
color red, TPIS_RAT and resi 108
color red, TPIS_RAT and resi 109
color red, TPIS_RAT and resi 112
color red, TPIS_RAT and resi 114
color red, TPIS_RAT and resi 120
color red, TPIS_RAT and resi 124
color red, TPIS_RAT and resi 130
color red, TPIS_RAT and resi 131
color red, TPIS_RAT and resi 135
color red, TPIS_RAT and resi 141
color red, TPIS_RAT and resi 142
color red, TPIS_RAT and resi 146
color red, TPIS_RAT and resi 149
color red, TPIS_RAT and resi 155
color red, TPIS_RAT and resi 156
color red, TPIS_RAT and resi 160
color red, TPIS_RAT and resi 161
color red, TPIS_RAT and resi 163
color red, TPIS_RAT and resi 175
color red, TPIS_RAT and resi 181
color red, TPIS_RAT and resi 183
color red, TPIS_RAT and resi 187
color red, TPIS_RAT and resi 188
color red, TPIS_RAT and resi 190
color red, TPIS_RAT and resi 193
color red, TPIS_RAT and resi 199
color red, TPIS_RAT and resi 201
color red, TPIS_RAT and resi 203
color red, TPIS_RAT and resi 206
color red, TPIS_RAT and resi 213
color red, TPIS_RAT and resi 216
color red, TPIS_RAT and resi 220
color red, TPIS_RAT and resi 221
color red, TPIS_RAT and resi 224
color red, TPIS_RAT and resi 227
color red, TPIS_RAT and resi 232
color red, TPIS_RAT and resi 238
color red, TPIS_RAT and resi 242
