color red, TPIS_HUMAN and resi 1
color red, TPIS_HUMAN and resi 4
color red, TPIS_HUMAN and resi 5
color red, TPIS_HUMAN and resi 13
color red, TPIS_HUMAN and resi 17
color red, TPIS_HUMAN and resi 18
color red, TPIS_HUMAN and resi 19
color red, TPIS_HUMAN and resi 20
color red, TPIS_HUMAN and resi 21
color red, TPIS_HUMAN and resi 28
color red, TPIS_HUMAN and resi 30
color red, TPIS_HUMAN and resi 32
color red, TPIS_HUMAN and resi 34
color red, TPIS_HUMAN and resi 52
color red, TPIS_HUMAN and resi 53
color red, TPIS_HUMAN and resi 54
color red, TPIS_HUMAN and resi 58
color red, TPIS_HUMAN and resi 63
color red, TPIS_HUMAN and resi 64
color red, TPIS_HUMAN and resi 89
color red, TPIS_HUMAN and resi 93
color red, TPIS_HUMAN and resi 98
color red, TPIS_HUMAN and resi 99
color red, TPIS_HUMAN and resi 108
color red, TPIS_HUMAN and resi 111
color red, TPIS_HUMAN and resi 117
color red, TPIS_HUMAN and resi 130
color red, TPIS_HUMAN and resi 134
color red, TPIS_HUMAN and resi 141
color red, TPIS_HUMAN and resi 146
color red, TPIS_HUMAN and resi 148
color red, TPIS_HUMAN and resi 155
color red, TPIS_HUMAN and resi 159
color red, TPIS_HUMAN and resi 174
color red, TPIS_HUMAN and resi 180
color red, TPIS_HUMAN and resi 182
color red, TPIS_HUMAN and resi 187
color red, TPIS_HUMAN and resi 192
color red, TPIS_HUMAN and resi 193
color red, TPIS_HUMAN and resi 199
color red, TPIS_HUMAN and resi 202
color red, TPIS_HUMAN and resi 218
color red, TPIS_HUMAN and resi 220
color red, TPIS_HUMAN and resi 223
color red, TPIS_HUMAN and resi 237
